# Generated by Django 5.0.4 on 2024-05-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100, verbose_name='Название')),
                ('car_body', models.CharField(choices=[('hatchback', 'хэтчбек'), ('saloon', 'седан'), ('estate', 'универсал'), ('convertible', 'кабриолет')], default='saloon', max_length=100, verbose_name='Кузов')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('grade', models.FloatField(verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
