# Generated by Django 5.0.4 on 2024-05-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_student_name_student_expelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_img',
            field=models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Фото'),
        ),
    ]
