# Generated by Django 5.0.4 on 2024-05-10 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car_car_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Марка машины')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_body',
            field=models.CharField(choices=[('hatchback', 'хэтчбек'), ('saloon', 'седан'), ('estate', 'универсал'), ('convertible', 'кабриолет')], max_length=100, null=True, verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_img',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='car',
            name='marka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.marka_car', verbose_name='Марка'),
        ),
    ]
